apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-api-deployment
  labels:
    app: feedback-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback-api
  template:
    metadata:
      labels:
        app: feedback-api
    spec:
      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: feedback-api-pvc
      containers:
      - name: feedback-api
        image: theolenglart/feedback-api
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_DIR
          value: "/usr/db"
        volumeMounts:
        - name: sqlite-storage
          mountPath: /usr/db
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20