apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: observability
data:
  consul.hcl: |
    datacenter = "dc1"
    data_dir = "/consul/data"

    server = true
    bootstrap_expect = 1

    ui_config {
      enabled = true
    }

    client_addr = "0.0.0.0"

    connect {
      enabled = true
    }
